
name: 'demo_dbt'
version: '1.3.1'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'demo_dbt'

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"



# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['dbt_project_evaluator', 'spark_utils', 'dbt_utils']
# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  demo_dbt:
    +bronze:
      materialized: table
      +schema: bronze
    silver:
      materialized: table
      +schema: silver
    gold:
      materialized: table
      +schema: gold



